[package]
name = "projectile"
version = "0.1.0"

[dependencies]
quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }

[[target.starknet-contract]]

[lib]
sierra = true  # Enable Sierra codegen.
casm = true   # Enable CASM codegen.